name: Daily Automatic Serial Booking

on:
  schedule:
    # 01:04 UTC == বাংলাদেশ সময় প্রতিদিন সকাল ০৭:০৪ AM
    - cron: '4 1 * * *'
  workflow_dispatch:

jobs:
  run-serial-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx playwright install chromium
      - run: node booking.js
