name: Daily Automatic Serial Booking

on:
  schedule:
    - cron: '5 1 * * *' # প্রতিদিন বাংলাদেশ সময় সকাল ৭:০৫ AM এ রান হবে
  workflow_dispatch:

jobs:
  book-serials:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install chromium

      - name: Run Serial Automation
        run: node booking.js
